# Generated by Django 4.2.25 on 2025-10-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=66)),
                ('last_name', models.CharField(max_length=66)),
                ('telegram_id', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=25)),
                ('secret_code', models.CharField(max_length=10, unique=True)),
                ('qr_code', models.ImageField(upload_to='client_img')),
                ('role', models.CharField(choices=[('directro', 'Direktor'), ('employee', 'Hodim'), ('client', 'Mijoz')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('loc_lat', models.FloatField()),
                ('loc_long', models.FloatField()),
                ('secret_code', models.CharField(max_length=10, unique=True)),
                ('qr_code', models.ImageField(upload_to='gym_img')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.BigIntegerField(default=0)),
                ('trainer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payment', to='main_app.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_payment', to='main_app.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_registration', to='main_app.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_registration', to='main_app.gym')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_registration', to='main_app.payment')),
            ],
        ),
    ]
