# Generated by Django 4.2.25 on 2025-11-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_trainer_payment_is_trainer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('telegram_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
