# Generated by Django 4.2.25 on 2025-11-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_admin_amount_admin_free_days_alter_client_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=66)),
                ('last_name', models.CharField(blank=True, max_length=66, null=True)),
                ('telegram_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=25)),
                ('language', models.CharField(choices=[('lotin', 'Lotincha'), ('kiril', 'Кирилча'), ('rus', ' Русский язык')], max_length=25)),
                ('secret_code', models.CharField(max_length=10, unique=True)),
                ('qr_code', models.ImageField(upload_to='worker_img')),
                ('is_director', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gym_worker', to='main_app.gym')),
            ],
        ),
    ]
