# Generated by Django 4.2.25 on 2025-11-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_client_user_name_client_uster_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='uster_name',
            new_name='user_name',
        ),
    ]
