# Generated by Django 4.2.25 on 2025-12-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_uster_name_client_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='card_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='card_number',
            field=models.CharField(default='1234567890', max_length=16),
            preserve_default=False,
        ),
    ]
