# Generated by Django 4.2.25 on 2025-12-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_gym_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='qr_code',
            field=models.ImageField(upload_to='qr_code_img'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='qr_code',
            field=models.ImageField(upload_to='qr_code_img'),
        ),
    ]
