# Generated by Django 4.2.25 on 2025-12-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_client_qr_code_alter_gym_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='qr_code',
            field=models.ImageField(upload_to=''),
        ),
    ]
