# Generated by Django 4.2.25 on 2026-01-23 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_date_and_gym_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 23, 10, 42, 36, 495138, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
