# Generated by Django 4.2.25 on 2026-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_admin_phone_number_alter_payment_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='worker_count',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
