# Generated by Django 4.2.25 on 2026-01-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_gym_worker_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='waiting_location',
            field=models.BooleanField(default=False),
        ),
    ]
