# Generated by Django 4.2.25 on 2026-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_gym_waiting_lump_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='gym_group_link',
            field=models.TextField(default=111),
            preserve_default=False,
        ),
    ]
