# Generated by Django 4.2.25 on 2026-04-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_admin_gym_group_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_registration', to='main_app.client'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_registration', to='main_app.payment'),
        ),
    ]
