# Generated by Django 4.2.25 on 2025-11-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='trainer',
            new_name='is_trainer',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='trainer',
            new_name='is_trainer',
        ),
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('lotin', 'Lotincha'), ('kiril', 'Кирилча'), ('rus', ' Русский язык')], default='2025-11-11', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='date_and',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='lump_sum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='lump_trainer_sum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_start',
            field=models.DateField(auto_now_add=True, default='2025-11-11'),
            preserve_default=False,
        ),
    ]
