# Generated by Django 4.2.25 on 2025-11-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_admin_alter_client_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admin',
            name='free_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('director', 'Direktor'), ('worker', 'Hodim'), ('client', 'Mijoz')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_payment', to='main_app.client'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_registration', to='main_app.client'),
        ),
    ]
