# Generated by Django 4.2.25 on 2025-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_client_role_alter_client_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_name',
        ),
        migrations.AddField(
            model_name='client',
            name='uster_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
