# Generated by Django 4.2.25 on 2025-12-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_admin_card_name_admin_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='secret_code',
        ),
    ]
