# Generated by Django 4.2.25 on 2025-12-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_worker_qr_code_remove_worker_secret_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
