# Generated by Django 4.2.25 on 2026-01-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_gym_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='lump_trainer_sum',
        ),
    ]
