# Generated by Django 4.2.25 on 2026-01-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_gym_lump_trainer_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='date_and',
            new_name='date_end',
        ),
    ]
