# Generated by Django 4.2.25 on 2026-01-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
