# Generated by Django 4.2.25 on 2026-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_gym_waiting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='waiting_lump_sum',
            field=models.BooleanField(default=False),
        ),
    ]
